"""
Architecture graph loader.

architecture.pkl was generated by src.data.microservice_generator.MicroserviceArchitecture
— a class that does not exist in our codebase.  We monkey-patch a stub class so that
pickle.load() succeeds, then extract the underlying networkx.DiGraph.

Graph structure (pre-build verified from inspect_arch.py):
  - 20 nodes  (integer IDs 0–19)
  - 68 directed edges with float weights 0.05–0.99
  - Node IDs match service_id in metrics/syscalls/logs CSVs
  - auth_service (18) has incoming edges from ALL other 18 non-logging services
  - logging (19) is called by every service — never a root cause
  - cache_1 (15) has ZERO incoming edges — isolated from all call chains

All graph tools translate service_name ↔ node_id using the loader's name_to_id map.

Phase 2 additions:
  - build_fused_graph(t_start, t_end): fuse static arch with dynamic trace evidence
  - get_fused_graph(t_start, t_end): cached accessor for fused graph
  Fused graph uses SERVICE NAME nodes (not int IDs) for direct tool use.
"""
import sys
import types
import pickle
from pathlib import Path

import networkx as nx
import pandas as pd

from ..config import ARCH_PKL, STATIC_GRAPH_WEIGHT, DYNAMIC_GRAPH_WEIGHT

# ── Internal state ───────────────────────────────────────────────────────────

_graph: nx.DiGraph | None = None
_fused_cache: dict[tuple, nx.DiGraph] = {}  # keyed by (t_start_iso, t_end_iso)


def _load_graph() -> nx.DiGraph:
    """Load architecture.pkl by stubbing out the missing src module."""
    # Create the minimum module hierarchy that pickle expects
    for mod_path in ["src", "src.data", "src.data.microservice_generator"]:
        if mod_path not in sys.modules:
            sys.modules[mod_path] = types.ModuleType(mod_path)

    class MicroserviceArchitecture:
        """Stub for the original generator class — only __setstate__ is needed."""
        def __setstate__(self, state: dict) -> None:
            self.__dict__.update(state)

    sys.modules["src.data.microservice_generator"].MicroserviceArchitecture = \
        MicroserviceArchitecture

    with open(ARCH_PKL, "rb") as fh:
        arch = pickle.load(fh)

    graph: nx.DiGraph = arch.dependency_graph
    return graph


# ── Public accessor ──────────────────────────────────────────────────────────

def get_arch_graph() -> nx.DiGraph:
    """Return the static architecture DiGraph (integer node IDs). Cached after first call."""
    global _graph
    if _graph is None:
        _graph = _load_graph()
        print(f"[graph_loader] Loaded architecture.pkl — "
              f"{len(_graph.nodes())} nodes, {len(_graph.edges())} edges.")
    return _graph


# ── Phase 2: Fused graph ─────────────────────────────────────────────────────

def build_fused_graph(
    t_start: "str | pd.Timestamp",
    t_end:   "str | pd.Timestamp",
) -> nx.DiGraph:
    """
    Fuse the static architecture graph with dynamic call evidence from traces.

    Edge weight scheme (plan §2.2):
      Both static + dynamic:  (static_w * STATIC_GRAPH_WEIGHT
                                + dyn_w_norm * DYNAMIC_GRAPH_WEIGHT) / 3.0
      Dynamic-only edge:      1.5  (observed in traces but absent from static model)
      Static-only edge:       0.5  (modelled but not observed in this window)

    Dynamic edge weights are call-count normalised to [0, 1] (max call = 1.0).
    Returns a DiGraph with SERVICE NAME nodes and edge attributes:
      static_weight, dynamic_weight, fused_weight.
    """
    # Lazy import to avoid circular dependency at module-init time
    from .loader import get_loader

    loader  = get_loader()
    t_start = pd.Timestamp(t_start) if not isinstance(t_start, pd.Timestamp) else t_start
    t_end   = pd.Timestamp(t_end)   if not isinstance(t_end,   pd.Timestamp) else t_end

    G_static = get_arch_graph()

    # ── Step 1: build dynamic edges from trace spans ─────────────────────────
    tr = loader.traces
    window = tr[(tr["start_time"] >= t_start) & (tr["start_time"] <= t_end)]

    edge_counts: dict[tuple[str, str], int] = {}
    if not window.empty:
        span_map = tr.set_index("span_id")["service_name"].to_dict()
        for _, row in window.iterrows():
            child = row["service_name"]
            pid   = row.get("parent_span_id")
            if pd.isna(pid):
                continue
            parent = span_map.get(str(pid))
            if parent is None or parent == child:
                continue
            key = (parent, child)
            edge_counts[key] = edge_counts.get(key, 0) + 1

    # Normalise dynamic weights to [0, 1]
    max_count = max(edge_counts.values(), default=1)
    dynamic_w: dict[tuple[str, str], float] = {
        k: v / max_count for k, v in edge_counts.items()
    }

    # ── Step 2: collect static edges (translate int IDs → service names) ─────
    static_w: dict[tuple[str, str], float] = {}
    for u_id, v_id, data in G_static.edges(data=True):
        u = loader.id_to_name.get(u_id, str(u_id))
        v = loader.id_to_name.get(v_id, str(v_id))
        static_w[(u, v)] = float(data.get("weight", 1.0))

    # ── Step 3: merge into fused graph ────────────────────────────────────────
    G = nx.DiGraph()
    G.add_nodes_from(loader.service_names)

    for key in set(static_w) | set(dynamic_w):
        u, v = key
        sw = static_w.get(key, 0.0)
        dw = dynamic_w.get(key, 0.0)

        if sw > 0 and dw > 0:
            fused = (sw * STATIC_GRAPH_WEIGHT + dw * DYNAMIC_GRAPH_WEIGHT) / 3.0
        elif dw > 0:
            fused = 1.5   # observed in traces but absent from static model
        else:
            fused = 0.5   # static-only: modelled but not observed in window

        G.add_edge(u, v,
                   static_weight=round(sw, 4),
                   dynamic_weight=round(dw, 4),
                   fused_weight=round(fused, 4))

    return G


def get_fused_graph(
    t_start: "str | pd.Timestamp",
    t_end:   "str | pd.Timestamp",
) -> nx.DiGraph:
    """Return a cached fused graph for the given window.  Builds on first call."""
    global _fused_cache
    ts = pd.Timestamp(t_start) if not isinstance(t_start, pd.Timestamp) else t_start
    te = pd.Timestamp(t_end)   if not isinstance(t_end,   pd.Timestamp) else t_end
    key = (ts.isoformat(), te.isoformat())
    if key not in _fused_cache:
        _fused_cache[key] = build_fused_graph(ts, te)
    return _fused_cache[key]
